version: '3.9'

networks:
  app-net:

services:

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@database/postgres
    networks:
      - app-net
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:17beta2-bullseye
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
    networks:
      - app-net